### ISSUE TITLE
Facing issue of False Positive Test Case Report

### ISSUE THREAD

**Issue by pramaanONDC** [ONDC-Official/pramaan#1398]
**Organisation Name:** Amnex

**Raised By:** [imdesai00](https://github.com/imdesai00)

**Test_id:** 1766398476125
**Id:** [ctubecknapibeta.amnex.com](copy:ctubecknapibeta.amnex.com)
**Version:** 2.0.1
**Environment:** Preprod
**Type:** BUS
**Domain:** ONDC:TRV11

**Tests:**
- **Flow ID:** MBL_8
  **Transaction ID:** [683425a3-0667-4e1b-af1c-22b1e6bd2139](copy:683425a3-0667-4e1b-af1c-22b1e6bd2139)
  **Type:** undefined

**Description:**
Facing issue of false positive test case report of TRV11 V2.0.1 as SELLER NP
1 fulfilment_id
2 fulfilment_type
3 fulfilment location obj
4 3 fulfilment location descriptor obj

In select, init confirm api & other.
Please check & Resolve.

**Comment by pramaanONDC** [comment]
### 🙌 Thank You for Reaching Out!

We've received your ticket and our team will get back to you shortly.

---

### 🕒 Support Hours
**Monday to Friday:** 10:00 AM - 6:00 PM IST<br>**Weekend Support:** Available for *planned cases only*<br>

---

### 📍Response Time *(For issues raised via GitHub only)*
- 🟢 **Normal Issues:** Response within **4 business hours**
- 🔴 **Critical Issues:** Response within **2 business hours**

---

### Support Call Schedule:

| 🛠 **Domain** | 🕒 **Schedule** | 🔗 **Join / Calendar Link** |
|--------------|----------------|:---------------------------:|
| 🛍 Retail & Logistics | Daily, 4:00-5:00 PM IST | [Join](https://meet.google.com/ntx-jbjg-ykj) |
| 🛺 Mobility | Book a Slot | [Mobility Calendar](https://calendar.app.google/sKav2Du1mWofYbfG7) |
| 💸 Financial Services | Book a Slot | [Financial Services Calendar](https://calendar.app.google/8fvADhXshu53tvQ38) |

**Comment by AmanSequelString** [comment]
Hi @Ganesh11772  this has been fixed, please confirm with NP

**Comment by imdesai00** [comment]
<img width="1908" height="832" alt="Image" src="https://github.com/user-attachments/assets/5031ad5c-4fb8-4f5b-a252-3511d7b08ce6" />

@AmanSequelString, the Generate Report issue again occurred. Please check & fix it.

**Comment by AmanSequelString** [comment]
Hi @imdesai00, I was able to successfully generate the report from Pramaan for testId: 1766398476125.
There might be an issue with the recent transaction on your end.
@Ganesh11772, please check the logs and share your findings.
Attaching the Pramaan-generated report for reference.

[Report for 1766398476125.zip](https://github.com/user-attachments/files/24364178/Report.for.1766398476125.zip)

**Comment by imdesai00** [comment]
hi @AmanSequelString i have tried with different transactionID, but still the same issue occurred.
