### ISSUE TITLE
FS | Working Capital | Flow initiation issues

### ISSUE THREAD

**Issue by y0geshb** [ONDC-Official/pramaan#91]
Additional Information:

1. Credit line assignment is complete, but the drawdown could not be initiated for seller testing. The flow is stuck, showing partial completion of on_init (67%) and on_confirm (50%), indicating that drawdown is not implemented.
2. In post-order flows, the process is stuck at the confirmation stage of credit line assignment. However, the flow should proceed with credit line drawdown before triggering missed EMI or any other post-order scenarios, which is currently missing.
3. The same issue persists for foreclosure and pre-payment scenarios.
4. For buyer testing of credit line drawdown, there is no input field for transaction ID. Since the flow is designed to start from init, it cannot be initiated without the required input.
5. Unable to download the report after it has been generated.

![Image](https://github.com/user-attachments/assets/f6d21c5e-8ef4-4612-b4d6-7758940561f1)
![Image](https://github.com/user-attachments/assets/6d4d4c20-4df7-43a5-be22-f26116bd2f2d)
![Image](https://github.com/user-attachments/assets/51248ae3-5265-454c-b901-7bb1c01e0ff8)

**Comment by y0geshb** [comment]
@simranOndc

**Comment by Aniketdhama** [comment]
@y0geshb  @simranOndc  The issue has been resolved successfully

**Comment by simranOndc** [comment]
@y0geshb please check once

**Comment by y0geshb** [comment]
Pointer #4: For Flow_1, there is no input field to capture the transaction ID for buyer testing. If Flow_1 is initiated more than 5 minutes prior, Flow_2 will not be triggered, as per the logic, and will throw a "no transaction found" error. This behavior was tested, and the above outcome was observed.

Pointer #5: Reports are still not being downloaded.

**Comment by simranOndc** [comment]
@Aniketdhama close all these pointers. You can connect with @y0geshb for clarity.

**Comment by simranOndc** [comment]
@Aniketdhama Please update the status

**Comment by Aniketdhama** [comment]
@simranOndc   Pointer 4 and 5 are pending, and we are currently working on them

**Comment by Aniketdhama** [comment]
@y0geshb  it is completed

**Comment by y0geshb** [comment]
Since the NP successfully downloaded and reviewed the report, this issue is now closed
